<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HPDA0017" ignored="0" name="Command line test" tests="20" failures="17" timestamp="09 Jul 2018 08:16:10 GMT" time="0.11" errors="0">
  <testcase name="Test10_Rotate_Array" time="0.02" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [{-4,-5,54,95,-14,-15,4,5}] but found [question1.MyCollection@7c0e2abd]">
      <![CDATA[java.lang.AssertionError: expected [{-4,-5,54,95,-14,-15,4,5}] but found [question1.MyCollection@7c0e2abd]
at testquestion1.Test_MyCollection.Test10_Rotate_Array(Test_MyCollection.java:94)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- Test10_Rotate_Array -->
  <testcase name="Test1_Able_To_Add_New_Entry_In_Collection" time="0.0" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assertion Failed : Not able to add number 5 in collection expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Failed : Not able to add number 5 in collection expected [true] but found [false]
at testquestion1.Test_MyCollection.Test1_Able_To_Add_New_Entry_In_Collection(Test_MyCollection.java:16)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- Test1_Able_To_Add_New_Entry_In_Collection -->
  <testcase name="Test2_Duplicate_Entry_In_Collection" time="0.01" classname="testquestion1.Test_MyCollection"/>
  <testcase name="Test3_Get_Collection_Functionality" time="0.0" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assertion Failed : Not able to read collection expected [{}] but found [question1.MyCollection@56f4468b]">
      <![CDATA[java.lang.AssertionError: Assertion Failed : Not able to read collection expected [{}] but found [question1.MyCollection@56f4468b]
at testquestion1.Test_MyCollection.Test3_Get_Collection_Functionality(Test_MyCollection.java:32)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- Test3_Get_Collection_Functionality -->
  <testcase name="Test4_DoubleCapacity" time="0.0" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assertion Failed : Not able to add number in collection once it get fulled expected [{4,5,-4,-5,6}] but found [question1.MyCollection@100fc185]">
      <![CDATA[java.lang.AssertionError: Assertion Failed : Not able to add number in collection once it get fulled expected [{4,5,-4,-5,6}] but found [question1.MyCollection@100fc185]
at testquestion1.Test_MyCollection.Test4_DoubleCapacity(Test_MyCollection.java:41)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- Test4_DoubleCapacity -->
  <testcase name="Test5_Remove_Functionality_If_Entry_Already_Present" time="0.0" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assetion Failed : Not Able to delete entry from collection expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assetion Failed : Not Able to delete entry from collection expected [true] but found [false]
at testquestion1.Test_MyCollection.Test5_Remove_Functionality_If_Entry_Already_Present(Test_MyCollection.java:50)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- Test5_Remove_Functionality_If_Entry_Already_Present -->
  <testcase name="Test6_Remove_Functionality_If_Collection_Is_Empty" time="0.0" classname="testquestion1.Test_MyCollection"/>
  <testcase name="Test7_Collection_Length_Functionality" time="0.0" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [6] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [0]
at testquestion1.Test_MyCollection.Test7_Collection_Length_Functionality(Test_MyCollection.java:67)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- Test7_Collection_Length_Functionality -->
  <testcase name="Test8_Search_Functionality_If_Enrty_Exists" time="0.0" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [4] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [0]
at testquestion1.Test_MyCollection.Test8_Search_Functionality_If_Enrty_Exists(Test_MyCollection.java:76)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- Test8_Search_Functionality_If_Enrty_Exists -->
  <testcase name="Test9_Search_Functionality_If_Enrty_Not_Exists" time="0.0" classname="testquestion1.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
at testquestion1.Test_MyCollection.Test9_Search_Functionality_If_Enrty_Not_Exists(Test_MyCollection.java:84)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- Test9_Search_Functionality_If_Enrty_Not_Exists -->
  <testcase name="Test10_Rotate_Array" time="0.02" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test10_Rotate_Array(Test_MyCollection.java:91)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test10_Rotate_Array -->
  <testcase name="Test1_Able_To_Add_New_Entry_In_Collection" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test1_Able_To_Add_New_Entry_In_Collection(Test_MyCollection.java:16)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test1_Able_To_Add_New_Entry_In_Collection -->
  <testcase name="Test2_Duplicate_Entry_In_Collection" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test2_Duplicate_Entry_In_Collection(Test_MyCollection.java:23)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test2_Duplicate_Entry_In_Collection -->
  <testcase name="Test3_Get_Collection_Functionality" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assertion Failed : Not able to read collection expected [{}] but found [question2.MyCollection@2a5ca609]">
      <![CDATA[java.lang.AssertionError: Assertion Failed : Not able to read collection expected [{}] but found [question2.MyCollection@2a5ca609]
at testquestion2.Test_MyCollection.Test3_Get_Collection_Functionality(Test_MyCollection.java:32)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- Test3_Get_Collection_Functionality -->
  <testcase name="Test4_DoubleCapacity" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test4_DoubleCapacity(Test_MyCollection.java:39)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test4_DoubleCapacity -->
  <testcase name="Test5_Remove_Functionality_If_Entry_Already_Present" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test5_Remove_Functionality_If_Entry_Already_Present(Test_MyCollection.java:48)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test5_Remove_Functionality_If_Entry_Already_Present -->
  <testcase name="Test6_Remove_Functionality_If_Collection_Is_Empty" time="0.0" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test7_Collection_Length_Functionality" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test7_Collection_Length_Functionality(Test_MyCollection.java:64)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test7_Collection_Length_Functionality -->
  <testcase name="Test8_Search_Functionality_If_Enrty_Exists" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test8_Search_Functionality_If_Enrty_Exists(Test_MyCollection.java:73)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test8_Search_Functionality_If_Enrty_Exists -->
  <testcase name="Test9_Search_Functionality_If_Enrty_Not_Exists" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at question2.MyCollection.search(MyCollection.java:30)
at question2.MyCollection.add(MyCollection.java:50)
at testquestion2.Test_MyCollection.Test9_Search_Functionality_If_Enrty_Not_Exists(Test_MyCollection.java:82)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Test9_Search_Functionality_If_Enrty_Not_Exists -->
</testsuite> <!-- Command line test -->
